/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.3 butterflies.glb --transform --types --shadows
*/

import * as THREE from 'three'
import React, { useEffect, useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    rig003: THREE.Mesh
    ['2']: THREE.SkinnedMesh
    rig012: THREE.Mesh
    ['1']: THREE.SkinnedMesh
    ['1001']: THREE.SkinnedMesh
    rig002: THREE.Mesh
    ['2001']: THREE.SkinnedMesh
    rig001: THREE.Mesh
    ['2002']: THREE.SkinnedMesh
    rig004: THREE.Mesh
    ['2003']: THREE.SkinnedMesh
    rig005: THREE.Mesh
    ['1002']: THREE.SkinnedMesh
    rig006: THREE.Mesh
    ['1003']: THREE.SkinnedMesh
    rig007: THREE.Mesh
    ['1004']: THREE.SkinnedMesh
    rig013: THREE.Mesh
    ['1005']: THREE.SkinnedMesh
    rig008: THREE.Mesh
    ['1006']: THREE.SkinnedMesh
    rig009: THREE.Mesh
    ['1007']: THREE.SkinnedMesh
    rig010: THREE.Mesh
    ['2004']: THREE.SkinnedMesh
    rig011: THREE.Mesh
    ['2005']: THREE.SkinnedMesh
    rig: THREE.Mesh
    ['2006']: THREE.SkinnedMesh
    Bone: THREE.Bone
    Bone_1: THREE.Bone
    neutral_bone: THREE.Bone
    neutral_bone_1: THREE.Bone
    Bone_2: THREE.Bone
    Bone_3: THREE.Bone
    Bone_4: THREE.Bone
    Bone_5: THREE.Bone
    Bone_6: THREE.Bone
    Bone_7: THREE.Bone
    Bone_8: THREE.Bone
    Bone_9: THREE.Bone
    Bone_10: THREE.Bone
    Bone_11: THREE.Bone
    Bone_12: THREE.Bone
    Bone_13: THREE.Bone
  }
  materials: {
    ['material.001']: THREE.MeshStandardMaterial
    material: THREE.MeshStandardMaterial
  }
}

type ActionName = 'action.001' | 'action.004' | 'action.002' | 'action.006' | 'action.007' | 'action.027' | 'action.011' | 'action.013' | 'action.015' | 'action.017' | 'action.019' | 'action.020' | 'action.023' | 'action.025'
type GLTFActions = Record<ActionName, THREE.AnimationAction>

function Model(props: JSX.IntrinsicElements['group']) {
  const group = useRef<THREE.Group>()
  const { nodes, materials, animations } = useGLTF('models/butterflies-transformed.glb') as GLTFResult
  const { actions } = useAnimations<GLTFActions>(animations, group)

  useEffect(() => {
    for (const action in actions) {
      actions[action].play()
    }
  }, [])
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="a" position={[15.32, 2.33, -11.01]} scale={1.43}>
          <mesh name="rig003" castShadow receiveShadow geometry={nodes.rig003.geometry} material={nodes.rig003.material} position={[-0.55, -0.13, 3.02]} rotation={[-1.2, 1.37, 0.53]} scale={0.02}>
            <group name="armature" position={[0.63, -0.15, 0.09]} rotation={[-Math.PI / 2, 0, 0]} scale={6.1}>
              <primitive object={nodes.Bone} />
              <skinnedMesh name="2" geometry={nodes['2'].geometry} material={materials['material.001']} skeleton={nodes['2'].skeleton} />
            </group>
          </mesh>
        </group>
        <group name="c" position={[14.7, -0.83, -8.86]} rotation={[Math.PI, -0.7, Math.PI]} scale={1.25}>
          <mesh name="rig012" castShadow receiveShadow geometry={nodes.rig012.geometry} material={nodes.rig012.material} position={[-3.36, -0.42, 2.81]} rotation={[-0.01, -0.43, 0.6]} scale={0.03}>
            <group name="armature001" position={[3.19, -0.49, 1.82]} rotation={[-Math.PI / 2, 0, 0]} scale={7.37}>
              <primitive object={nodes.Bone_1} />
              <primitive object={nodes.neutral_bone} />
              <primitive object={nodes.neutral_bone_1} />
              <skinnedMesh name="1" geometry={nodes['1'].geometry} material={materials.material} skeleton={nodes['1'].skeleton} />
              <skinnedMesh name="1001" geometry={nodes['1001'].geometry} material={materials.material} skeleton={nodes['1001'].skeleton} />
            </group>
          </mesh>
        </group>
        <group name="b" position={[16.94, -0.29, -9.61]} rotation={[Math.PI, -1.5, Math.PI]} scale={1.43}>
          <mesh name="rig002" castShadow receiveShadow geometry={nodes.rig002.geometry} material={nodes.rig002.material} position={[-0.54, -0.13, 3.02]} rotation={[-0.97, 1.39, 0.3]} scale={0.02}>
            <group name="armature002" position={[0.63, -0.15, 0.09]} rotation={[-Math.PI / 2, 0, 0]} scale={6.07}>
              <primitive object={nodes.Bone_2} />
              <skinnedMesh name="2001" geometry={nodes['2001'].geometry} material={materials['material.001']} skeleton={nodes['2001'].skeleton} />
            </group>
          </mesh>
        </group>
        <group name="d" position={[14.17, 1.28, -11.69]} scale={1.52}>
          <mesh name="rig001" castShadow receiveShadow geometry={nodes.rig001.geometry} material={nodes.rig001.material} position={[2.2, 0.08, 2.21]} rotation={[2.67, 1.22, -2.61]} scale={0.03}>
            <group name="armature003" position={[-1.33, 0, -0.54]} rotation={[-Math.PI / 2, 0, 0]} scale={4.69}>
              <primitive object={nodes.Bone_3} />
              <skinnedMesh name="2002" geometry={nodes['2002'].geometry} material={materials['material.001']} skeleton={nodes['2002'].skeleton} />
            </group>
          </mesh>
        </group>
        <group name="e" position={[13.23, -1, -9.72]} rotation={[0, 1.27, -0.34]} scale={1.52}>
          <mesh name="rig004" castShadow receiveShadow geometry={nodes.rig004.geometry} material={nodes.rig004.material} position={[2.2, 0.08, 2.21]} rotation={[2.67, 1.22, -2.61]} scale={0.03}>
            <group name="armature004" position={[-1.33, 0, -0.54]} rotation={[-Math.PI / 2, 0, 0]} scale={4.69}>
              <primitive object={nodes.Bone_4} />
              <skinnedMesh name="2003" geometry={nodes['2003'].geometry} material={materials['material.001']} skeleton={nodes['2003'].skeleton} />
            </group>
          </mesh>
        </group>
        <group name="f" position={[15.11, 0.57, -12.78]} rotation={[0, 1.23, 0]} scale={1.25}>
          <mesh name="rig005" castShadow receiveShadow geometry={nodes.rig005.geometry} material={nodes.rig005.material} position={[-1.67, -0.42, 2.8]} rotation={[0.04, -0.71, 0.63]} scale={0.03}>
            <group name="armature005" position={[3.19, -0.49, 1.82]} rotation={[-Math.PI / 2, 0, 0]} scale={7.37}>
              <primitive object={nodes.Bone_5} />
              <skinnedMesh name="1002" geometry={nodes['1002'].geometry} material={materials.material} skeleton={nodes['1002'].skeleton} />
            </group>
          </mesh>
        </group>
        <group name="g" position={[15.41, 0.72, -11.41]} rotation={[0, -0.06, 0]} scale={1.25}>
          <mesh name="rig006" castShadow receiveShadow geometry={nodes.rig006.geometry} material={nodes.rig006.material} position={[-3.86, 2.01, 2.79]} rotation={[1.16, 0.25, 0.19]} scale={0.03}>
            <group name="armature006" position={[3.19, -0.49, 1.82]} rotation={[-Math.PI / 2, 0, 0]} scale={7.37}>
              <primitive object={nodes.Bone_6} />
              <skinnedMesh name="1003" geometry={nodes['1003'].geometry} material={materials.material} skeleton={nodes['1003'].skeleton} />
            </group>
          </mesh>
        </group>
        <group name="h" position={[17.14, -0.8, -7.61]} rotation={[-Math.PI, -1.33, -3.08]} scale={1.25}>
          <mesh name="rig007" castShadow receiveShadow geometry={nodes.rig007.geometry} material={nodes.rig007.material} position={[-3.93, 0.78, 2.29]} rotation={[0.61, 0.3, 0.44]} scale={0.03}>
            <group name="armature007" position={[3.19, -0.49, 1.82]} rotation={[-Math.PI / 2, 0, 0]} scale={3.68}>
              <primitive object={nodes.Bone_7} />
              <skinnedMesh name="1004" geometry={nodes['1004'].geometry} material={materials.material} skeleton={nodes['1004'].skeleton} />
            </group>
          </mesh>
        </group>
        <group name="i" position={[18.46, -0.8, -13.5]} rotation={[0, 0.72, 0]} scale={1.25}>
          <mesh name="rig013" castShadow receiveShadow geometry={nodes.rig013.geometry} material={nodes.rig013.material} position={[-7.51, -0.35, 2.81]} rotation={[-0.15, 0.76, 0.7]} scale={0.03}>
            <group name="armature008" position={[3.19, -0.49, 1.82]} rotation={[-Math.PI / 2, 0, 0]} scale={7.37}>
              <primitive object={nodes.Bone_8} />
              <skinnedMesh name="1005" geometry={nodes['1005'].geometry} material={materials.material} skeleton={nodes['1005'].skeleton} />
            </group>
          </mesh>
        </group>
        <group name="j" position={[17.95, 2.06, -9.22]} rotation={[0, -0.85, 0.83]} scale={1.25}>
          <mesh name="rig008" castShadow receiveShadow geometry={nodes.rig008.geometry} material={nodes.rig008.material} position={[-3.36, 2.71, 2.78]} rotation={[1.15, 0.09, -1.27]} scale={0.03}>
            <group name="armature009" position={[3.19, -0.49, 1.82]} rotation={[-Math.PI / 2, 0, 0]} scale={7.37}>
              <primitive object={nodes.Bone_9} />
              <skinnedMesh name="1006" geometry={nodes['1006'].geometry} material={materials.material} skeleton={nodes['1006'].skeleton} />
            </group>
          </mesh>
        </group>
        <group name="k" position={[13.37, -0.8, -12.6]} rotation={[0, 1.56, 0.22]} scale={1.25}>
          <mesh name="rig009" castShadow receiveShadow geometry={nodes.rig009.geometry} material={nodes.rig009.material} position={[-7.39, 0.17, 2.76]} rotation={[0.28, 0.64, 0.45]} scale={0.03}>
            <group name="armature010" position={[3.19, -0.49, 1.82]} rotation={[-Math.PI / 2, 0, 0]} scale={7.37}>
              <primitive object={nodes.Bone_10} />
              <skinnedMesh name="1007" geometry={nodes['1007'].geometry} material={materials.material} skeleton={nodes['1007'].skeleton} />
            </group>
          </mesh>
        </group>
        <group name="l" position={[14.03, 0.87, -9.02]} rotation={[Math.PI, 0, 2.8]} scale={1.52}>
          <mesh name="rig010" castShadow receiveShadow geometry={nodes.rig010.geometry} material={nodes.rig010.material} position={[1.82, 1.17, 2.14]} rotation={[2.15, 0.93, -2.14]} scale={0.03}>
            <group name="armature011" position={[-1.33, 0, -0.54]} rotation={[-Math.PI / 2, 0, 0]} scale={4.69}>
              <primitive object={nodes.Bone_11} />
              <skinnedMesh name="2004" geometry={nodes['2004'].geometry} material={materials['material.001']} skeleton={nodes['2004'].skeleton} />
            </group>
          </mesh>
        </group>
        <group name="m" position={[14.85, 0.52, -4.86]} rotation={[3.07, 1.11, 2.84]} scale={1.52}>
          <mesh name="rig011" castShadow receiveShadow geometry={nodes.rig011.geometry} material={nodes.rig011.material} position={[4.11, 0.05, 3.03]} rotation={[2.95, 0.22, -3.01]} scale={0.03}>
            <group name="armature012" position={[-1.33, 0, -0.54]} rotation={[-Math.PI / 2, 0, 0]} scale={4.69}>
              <primitive object={nodes.Bone_12} />
              <skinnedMesh name="2005" geometry={nodes['2005'].geometry} material={materials['material.001']} skeleton={nodes['2005'].skeleton} />
            </group>
          </mesh>
        </group>
        <group name="n" position={[15.77, 0.04, -9.64]} rotation={[0, -1.35, -0.34]} scale={1.52}>
          <mesh name="rig" castShadow receiveShadow geometry={nodes.rig.geometry} material={nodes.rig.material} position={[1.82, 1.17, 2.14]} rotation={[2.15, 0.93, -2.14]} scale={0.03}>
            <group name="armature013" position={[-1.33, 0, -0.54]} rotation={[-Math.PI / 2, 0, 0]} scale={6.1}>
              <primitive object={nodes.Bone_13} />
              <skinnedMesh name="2006" geometry={nodes['2006'].geometry} material={materials['material.001']} skeleton={nodes['2006'].skeleton} />
            </group>
          </mesh>
        </group>
      </group>
    </group>
  )
}

export default Model;

useGLTF.preload('models/butterflies-transformed.glb')
